CREATE DATABASE transit;

use transit;

CREATE TABLE User (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Mot_de_passe VARCHAR(255) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    Date_Update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Date_Creation DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Document (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Id_User INT NOT NULL,
    Nom_document VARCHAR(255) NOT NULL,
    Chemin_stockage VARCHAR(500) NOT NULL,
    Tailles_MB DOUBLE NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    Date_Update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Date_Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_user FOREIGN KEY (Id_User) REFERENCES User (ID) ON DELETE CASCADE
);

CREATE TABLE Lien (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Id_Document INT NOT NULL,
    Code_unique VARCHAR(255) NOT NULL UNIQUE,
    URL VARCHAR(500) NOT NULL,
    Nb_Acces INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    Date_Expiration DATETIME NULL,
    Date_Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lien_document FOREIGN KEY (Id_Document) REFERENCES Document (ID) ON DELETE CASCADE
);

CREATE TABLE Parametre_User (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Id_User INT NOT NULL UNIQUE,
    Notification_Mail BOOLEAN DEFAULT TRUE,
    Langue VARCHAR(10) DEFAULT 'fr',
    Date_Update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Date_Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paramuser_user FOREIGN KEY (Id_User) REFERENCES User (ID) ON DELETE CASCADE
);

CREATE TABLE Parametre_Document (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Id_Document INT NOT NULL UNIQUE,
    Protection_MotDePasse BOOLEAN DEFAULT FALSE,
    Mot_de_passe VARCHAR(255),
    Date_Expiration DATETIME NULL,
    Date_Update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Date_Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paramdocument_document FOREIGN KEY (Id_Document) REFERENCES Document (ID) ON DELETE CASCADE
);

CREATE TABLE Historique (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Id_Lien INT NOT NULL,
    Action VARCHAR(255) NOT NULL,
    Adresse_IP VARCHAR(50) NOT NULL,
    Date_Update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Date_Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historique_lien FOREIGN KEY (Id_Lien) REFERENCES Lien (ID) ON DELETE CASCADE
);